global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100', '172.17.0.0:9100']
  - job_name: 'Docker Containers'
    static_configs:
      - targets: ['172.17.0.0:8080']
